### PR TITLE
paper: Resurrecting bbh with kinematic shapes

### PR DESCRIPTION
**Pull request by talismanbrandi**
Add [Resurrecting bb¯h with kinematic shapes](https://inspirehep.net/literature/1833995).

```
* Add reference to 'Resurrecting bb¯h with kinematic shapes'
   - c.f. https://arxiv.org/abs/2011.13945
* Add link to sections: physics-inspired basis, feature ranking, interpretability
```

Resurrecting $b\bar{b}h$ with kinematic shapes (https://arxiv.org/abs/2011.13945) addresses the question of measuring b-Yukawa from the bbh process at HL-LHC and FCC. We use an interpretable machine learning framework with a physics-inspired basis and use Shapley values for understanding variable importance and correlations.

Authors: Christophe Grojean, @talismanbrandi, and Zhuoni Qian

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Thanks for your PR @talismanbrandi &mdash; your contributions are appreciated! Could you please elaborate more though on why you think this paper belongs in the review? You mention that

> We use an interpretable machine learning framework with a physics-inspired basis

yet nowhere in the paper is this described. The paper doesn't contain any mention of machine learning of any sort that I can see. So while I don't doubt that your paper is excellent work I'm not sure what you hope the community might gain or learn from having it in the review given that machine learning isn't discussed.

Can you explain more?

For the time being I'm going to place this PR in "draft" mode, and if we don't hear back from you in a week I'll close it. :+1:

**Review by matthewfeickert — CHANGES_REQUESTED** [review]
Thanks for your PR @talismanbrandi &mdash; your contributions are appreciated! Could you please elaborate more though on why you think this paper belongs in the review? You mention that

> We use an interpretable machine learning framework with a physics-inspired basis

yet nowhere in the paper is this described. The paper doesn't contain any mention of machine learning of any sort that I can see. So while I don't doubt that your paper is excellent work I'm not sure what you hope the community might gain or learn from having it in the review given that machine learning isn't discussed.

Can you explain more?

For the time being I'm going to place this PR in "draft" mode, and if we don't hear back from you in a week I'll close it. :+1:

**Comment by matthewfeickert** [comment]
> The paper doesn't contain any mention of machine learning of any sort that I can see. So while I don't doubt that your paper is excellent work I'm not sure what you hope the community might gain or learn from having it in the review given that machine learning isn't discussed.

Ah. @talismanbrandi looking at your PR now it seems that you PR body and the content don't align. The PR body mentions https://arxiv.org/abs/2012.07740, but the PR itself is for https://arxiv.org/abs/2011.13945. Can you please correct the PR body?

**Comment by talismanbrandi** [comment]
Hi @matthewfeickert, trust me to mess this up in one way or the other. Yes, indeed it is https://arxiv.org/abs/2011.13945. The other paper comes nowhere close to using ML. I have amended the commit message and other parts that contained the wrong reference. Hope everything is ok now. Thanks!

**Comment by matthewfeickert** [comment]
> trust me to mess this up in one way or the other. Yes, indeed it is https://arxiv.org/abs/2011.13945. The other paper comes nowhere close to using ML. I have amended the commit message and other parts that contained the wrong reference. Hope everything is ok now. Thanks!

No worries @talismanbrandi! We've all been there before (if not multiple times). :slightly_smiling_face:  This all looks great, so thanks very much for your contribution! I see that there's a small conflict with the `HEPML.bib` though at the moment. Would you mind rebasing your fork's branch against the main project's `master`? That should take care of it.

I can also take care of this in the morning my time (US). :+1:

**Comment by talismanbrandi** [comment]
Thanks @matthewfeickert! I did some voodoo and it should have worked. However, the PR has become quite convoluted. If its better, I can close this PR and open a new one. Let me know.

**Comment by matthewfeickert** [comment]
> However, the PR has become quite convoluted. If its better, I can close this PR and open a new one. Let me know.

No, it's fine. I see what happened and as I have push rights to your fork I'll just clean this up with a quick rebase after lunch. :+1: This is all good to go after that, so you're good on your side. Thanks very much for your PR! :rocket:

**Comment by talismanbrandi** [comment]
Thanks @matthewfeickert!

**Comment by matthewfeickert** [comment]
@talismanbrandi I did drop the addition of the "$b$-Yukawa measurememts" segment here but **not** because I'm opposed to it. It is just probably a good idea for us to review and discuss new topics in the review so that there isn't an growth of hyper specialized topics over time. If you open up an Issue for discussion we'd be happy to discuss this further, and if you link this PR for refrence it will be helpful. :+1:

**Pull request merged**
