### PR TITLE
added papers May-Jun  23

### PR DESCRIPTION
**Pull request by wesmail**
Start date: 2023-05-08
End date:  2023-06-23

### CODE REVIEW

**Comment by jraine** [comment]
Hi Waleed, could you please order the bib entries in HEPML.bib in decreasing chronological order - for the `recent.md` generation to work correctly it assumes this.

At the moment the page goes "May, June, May", and so on.


Also I don't think we want about.md to change in this PR removing the moderators. This night require a change in made_py which we can fix in another PR.

Thanks!
Johnny

**Comment by ramonpeter** [comment]
There are some conflicts which need to be resolved before merging.

**Comment by ramonpeter** [comment]
> Hi Waleed, could you please order the bib entries in HEPML.bib in decreasing chronological order - for the `recent.md` generation to work correctly it assumes this.
> 
> At the moment the page goes "May, June, May", and so on.
> 
> Also I don't think we want about.md to change in this PR removing the moderators. This night require a change in made_py which we can fix in another PR.
> 
> Thanks! Johnny

The change of the moderators in the writing of about.md has been fixed yesterday already by me. So if you pull the latest commit, this should be correct now.

**Comment by ramonpeter** [comment]
@wesmail,
can you check this pull request again? It seems that before pushing there was not everything merged from previous
commits.

**Comment by ramonpeter** [comment]
I close it at and referee to my fix #179

**Pull request closed without merging**
