### PR TITLE
paper: Add topology classification with deep learning to improve real-time event selection

### PR DESCRIPTION
**Pull request by vlimant**
it seems that this early paper was omitted

### CODE REVIEW

**Comment by matthewfeickert** [comment]
This is blocked by Issue #24, but will get looked at once that's resolved.

**Comment by matthewfeickert** [comment]
@vlimant In the meantime, can you please rename the PR title to something descriptive?

**Comment by matthewfeickert** [comment]
@vlimant Thanks. Can you rebase this again `master` now that Ben has patched things.

**Comment by vlimant** [comment]
rebased

**Pull request merged**
