### PR TITLE
WIP: adding hep-lat since Nov 2022 and dump_bibtex_from_arxiv.py

### PR DESCRIPTION
**Pull request by etiennedreyer**
- Adding 2 hep-lat entries to `HEPML.bib` and `HEPML.tex` 
- Adding 14 hep-th entries but need feedback to know what to do with them (marked "beyond scope?" in `HEPML.bib`)
- Added modified version of script from @wesmail for dumping .bib entries from arXiv IDs (very helpful)

### CODE REVIEW

**Comment by ramonpeter** [comment]
Hi @etiennedreyer,
thanks for this. Do I get this right, that those entries marked with "beyond scope" are not mentioned anywhere
in the HEPML.tex file?

We should try put them in, otherwise they will not show up anywhere. Do you feel they need a new section?

**Comment by jraine** [comment]
> Building up on the discussion on slack we need to decide, whether we want to extend the scope of the LivingReview to also include ML paper from hep-th. If so, as suggested by @claudius-krause, we probably need to add some additional sections like:
> 
>     * Physics for AI
> 
>     * AI for hep-th
> 
> 
> to accommodate the papers within the latex file. In contrast @etiennedreyer suggested the section
> 
>     * ML for string theory
> 
> 
> but also argued that adding hep-th with its subtopic might make the LivingReview to broad? What do you guys think? In my opinion its part of HEP and should be included, but this should be a decision by a majority and not just by me. @bnachman @matthewfeickert @jraine

Looking at the current .bib file we only have 4 papers in hep-th, given that I think we should probably merge this PR as is without the hep-th entries (if there is no obvious category they fit into perhaps leaving them out of the .bib for now) and then move discussion of how to incorporate hep-th papers to another issue or combine it with the reordering of sections in a future rework.

I think we should try and accommodate them, but we may need to also go back more than 6 months on arxiv to capture all of the potential hep-th ML papers, and perhaps getting all of them at once makes it clearer what sections to include.

**Comment by bnachman** [comment]
I vote to include these papers!  I don't have a strong preference for the implementation.  For now, since there are so few, it may be fine to simply have a catch-all category topic like "formal theory and ML" which can imply both directions.

**Comment by claudius-krause** [comment]
Ok, let's include them like @bnachman suggested. 

Since I want to keep things on topic: I left out references to Forestano:2023ijh and Dersy:2023job in the .tex file of the July/August update, since the new category was not created yet. These two references are in the .bib file.

**Review by ramonpeter — APPROVED** [review]

**Pull request merged**
