### PR TITLE
Three papers from Weizmann Inst. et al.

### PR DESCRIPTION
**Pull request by etiennedreyer**
The first and last commits are standard. The second commit includes a new subcategory ("Set transformer") under "Generative models / density estimation", since the existing ones do not well describe our approach. Screenshot is attached.

new_category

### CODE REVIEW

**Comment by bnachman** [comment]
Hi @etiennedreyer thank you for your contribution!  For the label of the generative model, I wonder if we should pick something instead based on the training setup and not the architecture.  Transformers can be used for other generative models - it seems like the distinguishing feature here is how the model is trained?  Your setup seems GAN-like, where the discriminator is replaced with a non-trainable density comparison.  Is that correct?

**Comment by etiennedreyer** [comment]
Hi @bnachman thanks for helping think this one through. I asked the team and we felt that categorizing our approach under the "GAN" section would not capture it correctly, since there is no adversarial component, and even our reference model is a cVAE. It's a good point that transformer blocks can be introduced for other architectures as well, which is why we felt that "Set transformer" is a more descriptive subsection header, albeit somewhat specific. Let me know if you have a further suggestion... perhaps we can make a generic "Other" category for architectures?

**Comment by bnachman** [comment]
Hi @etiennedreyer I like the idea of an "other" category - let's go with that!  (alternative: "hybrid" or "other/hybrid"?)

**Comment by etiennedreyer** [comment]
Hi @bnachman , I got around to adding the "other/hybrid" section under generative models:
image
Please let me know if there's any other action item.

**Comment by etiennedreyer** [comment]
Hi @bnachman just a friendly ping about this. Also #131 needs review in order to fix the bug affecting the classification section.

**Review by ramonpeter — APPROVED** [review]

**Pull request merged**
